parameters:
     stripe_client.class: W3sami\StripeBundle\Services\StripeClient

services:
     W3sami\StripeBundle\Services\StripeClient: "@stripe_client"
     stripe_client:
         class:     "%stripe_client.class%"
         arguments: ["%w3sami.stripe.stripe_private_key%"]
         autowire: true
